### ISSUE TITLE
Lazy loading that webpack require 0.chunk.js is invalid url

### ISSUE THREAD

**Issue by vinhbt** [lbialy/play-ng2-webpack2#5]
inline.bundle.js:92:33 require /0.chunk.js but 0.chunk.js locate in sbt in /assets/0.chunk.js ==>
-----------------------------------------
EXCEPTION: Uncaught (in promise): Error: Loading chunk 0 failed.
Error: Loading chunk 0 failed.
    at HTMLScriptElement.onScriptComplete (http://localhost:9000/assets/inline.bundle.js:92:33) [angular]
    at HTMLScriptElement.wrapFn (http://localhost:9000/assets/polyfills.bundle.js:7053:29) [angular]
    at Object.onInvokeTask (http://localhost:9000/assets/vendor.bundle.js:28837:37) [angular]
    at ZoneDelegate.invokeTask (http://localhost:9000/assets/polyfills.bundle.js:6225:36) [angular]
    at Zone.runTask (http://localhost:9000/assets/polyfills.bundle.js:6029:47) [<root> => angular]
    at HTMLScriptElement.ZoneTask.invoke (http://localhost:9000/assets/polyfills.bundle.js:6279:38) [<root>]

**Comment by lbialy** [comment]
Could you provide some more information? In what circumstances did this happen?

**Comment by lbialy** [comment]
Closing for lack of activity.
